version: "3.5"

services:

  gitea:
    image: gitea/gitea:${GITEA_VERSION}
    container_name: "gitea"
    restart: "unless-stopped"
    env_file:
      - "../global.env"
      - "./gitea.env"
    networks:
      - traefik_net
    ports:
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ${GITEA_DATA_DIR}:/data
      - ${GITEA_CONFIG}:/data/gitea/conf/app.ini:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gitea.tls.domains[0].main=${TRAEFIK_DOMAIN}"
      - "traefik.http.routers.gitea.tls.domains[0].sans=*.${TRAEFIK_DOMAIN}"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

networks:
  traefik_net:
    external: true
