version: "3.5"

services:

  portainer:
    image: "portainer/portainer-ce:${PORTAINER_VERSION}"
    container_name: "portainer"
    restart: "unless-stopped"
    env_file:
      - "../global.env"
    networks:
      - traefik_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.tls.domains[0].main=${TRAEFIK_DOMAIN}"
      - "traefik.http.routers.portainer.tls.domains[0].sans=*.${TRAEFIK_DOMAIN}"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
    external: true

networks:
  traefik_net:
    external: true
